### ISSUE TITLE
最近代码运行出错

### ISSUE THREAD

**Issue by aleafboat** [winnerineast/CNNChineseClassifyer#1]
Traceback (most recent call last):
  File "./train.py", line 107, in <module>
    grad_hist_summary = tf.summary.histogram("{}/grad/hist".format(v.name), g)
AttributeError: 'module' object has no attribute 'histogram'

**Comment by winnerineast** [comment]
which version of tensorflow is being used? I updated tensorflow to 0.12.0rc1 which is almost the latest master branch. If you use any older version of tensorflow, please rollback to my previous version.

**Comment by winnerineast** [comment]
I didn't have @aleafboat 's feedback for months and close this issue.
